### ISSUE TITLE
Couldn't launch the app on centOS 6

### ISSUE THREAD

**Issue by immnk** [openfin/openfin-cli#43]
I have tried launching the app using the command `openfin --launch --url https://apple.com` and it gives the following error

```
[sgxbtdev@sgxbt-dev test-app]$ openfin --launch --url https://apple.com
/usr/lib/node_modules/openfin-cli/index.js:56
async function launchOpenfin(config) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/openfin-cli/cli.js:5:18)
```

I am running behind a company proxy server and have already set my **HTTPS_PROXY** and **strict_ssl** flags

What should I do to solve this?

**Comment by DasunUdana** [comment]
What is node version you are running? 
Upgrade to latest node version and try.

**Comment by immnk** [comment]
I have tried to node v10 and it isn’t working on it. I guess it’s something to do with proxy because I’m able to launch it at my home wifi
